import os

OFFLINE_MODE = os.getenv("OFFLINE_MODE", "false").lower() == "true"
OPCUA_SERVER_URL = "opc.tcp://192.168.10.70:4840"

VARIABLES = {
    "rio_comflt": "ns=1;s=R1:AMS_OBI_RIO_ComFlt",
    "evi_p1_comok": "ns=1;s=R1:EVI_P1.OBI.ComOk",
    "evi_p2_comok": "ns=1;s=R1:EVI_P2.OBI.ComOk",
    "evi_p3_comok": "ns=1;s=R1:EVI_P3.OBI.ComOk",
    "evi_p4_comok": "ns=1;s=R1:EVI_P4.OBI.ComOk",

    "bess_comflt": "ns=1;s=R1:ams_obi_jbox_comflt",
    "jbox": "ns=1;s=R1:JBOX_B_ComOk",
    "hmi_service_12": "ns=1;s=R1:HMI_OBI_ComFault_HMIService12", 
    "cs_service_12": "ns=1;s=R1:AMS_OBI_OCPP201_Wdg_ComFlt_CS1",
    "hmi_service_34": "ns=1;s=R1:HMI_OBI_ComFault_HMIService34",
    "cs_service_34": "ns=1;s=R1:AMS_OBI_OCPP201_Wdg_ComFlt_CS2",
    "dcbm1_comflt": "ns=1;s=R1:dcbm1.obi.comflt",
    "dcbm2_comflt": "ns=1;s=R1:dcbm2.obi.comflt",
    "dcbm3_comflt": "ns=1;s=R1:dcbm3.obi.comflt",
    "dcbm4_comflt": "ns=1;s=R1:dcbm4.obi.comflt",
    
    "seq12_ready": "ns=1;s=R1:seq12.b_ready",
    "seq12_fault": "ns=1;s=R1:SEQ12_OBI_ICPCFlt",
    "seq12_ic": "ns=1;s=R1:SEQ12.OLI.A.IC1",
    "seq12_pc": "ns=1;s=R1:SEQ12.OLI.A.PC1",
    "seq12_branch": "ns=1;s=R1:SEQ12.OLI.Branch_01",
    "seq12_ack": "ns=1;s=R1:seq12.ibi.ackcmd",
    "seq12_hmi": "ns=1;s=R1:SEQ12HMI.OLI.Branch_01",

    "hc1p1_current": "ns=1;s=R1:hc1.ori.hb1measi",
    "hc1p1_voltage": "ns=1;s=R1:hc1.ori.hb1measv",
    "pdc1_plim": "ns=1;s=R1:PDCx_R_PLim[1]",
    
    "evi1_cp_status": "ns=1;s=R1:EVI_P1.OLI.CP_StatusCode",
    "evi1_substatus": "ns=1;s=R1:EVI_P1.OLI.CP_SubStatusCode",
    "evi1_error": "ns=1;s=R1:EVI_P1.OLI.CP_ErrorCode",
    "evi1_pilot": "ns=1;s=R1:EVI_P1.OLI.PilotStatusCode",
    "evi1_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_MeasVDC",
    "evi1_target_current": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCCurrent",
    "evi1_target_voltage": "ns=1;s=R1:EVI_P1.OLI.EVSE_OutDCVoltage",
    "evi1_soc": "ns=1;s=R1:EVI_P1.OLI.SOC",
    "evi1_ack": "ns=1;s=R1:B_Ack",
    "evi1_es": "ns=1;s=R1:B_ES",
    "evi1_temp1": "ns=1;s=R1:EVI_P1.OLI.Temp1",
    "evi1_temp2": "ns=1;s=R1:EVI_P1.OLI.Temp2",
    "dcbm1_temp_h": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureH",
    "dcbm1_temp_l": "ns=1;s=R1:DCBM1.LiveMesure.TemperatureL",
    
    "seq13_ready": "ns=1;s=R1:seq13.b_ready",
    "seq13_fault": "ns=1;s=R1:SEQ13_OBI_ICPCFlt",
    "seq13_ic": "ns=1;s=R1:SEQ13.OLI.A.IC1",
    "seq13_pc": "ns=1;s=R1:SEQ13.OLI.A.PC1",
    "seq13_branch": "ns=1;s=R1:SEQ13.OLI.Branch_01",
    "seq13_ack": "ns=1;s=R1:seq13.ibi.ackcmd",
    "seq13_hmi": "ns=1;s=R1:SEQ13HMI.OLI.Branch_01",

    "hc2p3_current": "ns=1;s=R1:hc2.ori.hb1measi",
    "hc2p3_voltage": "ns=1;s=R1:hc2.ori.hb1measv",
    "pdc3_plim": "ns=1;s=R1:PDCx_R_PLim[3]",
    
    "evi3_cp_status": "ns=1;s=R1:EVI_P3.OLI.CP_StatusCode",
    "evi3_substatus": "ns=1;s=R1:EVI_P3.OLI.CP_SubStatusCode",
    "evi3_error": "ns=1;s=R1:EVI_P3.OLI.CP_ErrorCode",
    "evi3_pilot": "ns=1;s=R1:EVI_P3.OLI.PilotStatusCode",
    "evi3_voltage": "ns=1;s=R1:EVI_P3.OLI.EVSE_MeasVDC",
    "evi3_target_current": "ns=1;s=R1:EVI_P3.OLI.EVSE_OutDCCurrent",
    "evi3_target_voltage": "ns=1;s=R1:EVI_P3.OLI.EVSE_OutDCVoltage",
    "evi3_soc": "ns=1;s=R1:EVI_P3.OLI.SOC",
    "evi3_ack": "ns=1;s=R1:B_Ack3",
    "evi3_es": "ns=1;s=R1:B_ES3",
    "evi3_temp1": "ns=1;s=R1:EVI_P3.OLI.Temp1",
    "evi3_temp2": "ns=1;s=R1:EVI_P3.OLI.Temp2",
    "dcbm3_temp_h": "ns=1;s=R1:DCBM3.LiveMesure.TemperatureH",
    "dcbm3_temp_l": "ns=1;s=R1:DCBM3.LiveMesure.TemperatureL",
    
    "seq04_branch": "ns=1;s=R1:SEQ04.OLI.Branch_01",
    "seq04_start": "ns=1;s=R1:seq04.ibi.startcmd",
    "seq04_stop": "ns=1;s=R1:seq04.ibi.stopcmd",
    "seq04_ack": "ns=1;s=R1:seq04.ibi.ackcmd",
    "seq04_ic": "ns=1;s=R1:SEQ04.OLI.A.IC1",
    "seq04_pc": "ns=1;s=R1:SEQ04.OLI.A.PC1",
    "seq04_ready": "ns=1;s=R1:seq04.b_ready",
    "seq04_fault": "ns=1;s=R1:SEQ04_OBI_ICPCFlt",
    
    "seq22_ready": "ns=1;s=R1:seq22.b_ready",
    "seq22_fault": "ns=1;s=R1:SEQ22_OBI_ICPCFlt",
    "seq22_ic": "ns=1;s=R1:SEQ22.OLI.A.IC1",
    "seq22_pc": "ns=1;s=R1:SEQ22.OLI.A.PC1",
    "seq22_branch": "ns=1;s=R1:SEQ22.OLI.Branch_01",
    "seq22_ack": "ns=1;s=R1:seq22.ibi.ackcmd",
    "seq22_hmi": "ns=1;s=R1:SEQ22HMI.OLI.Branch_01",

    "hc1p2_current": "ns=1;s=R1:hc1.ori.hb2measi",
    "hc1p2_voltage": "ns=1;s=R1:hc1.ori.hb2measv",
    "pdc2_plim": "ns=1;s=R1:PDCx_R_PLim[2]",
    
    "evi2_cp_status": "ns=1;s=R1:EVI_P2.OLI.CP_StatusCode",
    "evi2_substatus": "ns=1;s=R1:EVI_P2.OLI.CP_SubStatusCode",
    "evi2_error": "ns=1;s=R1:EVI_P2.OLI.CP_ErrorCode",
    "evi2_pilot": "ns=1;s=R1:EVI_P2.OLI.PilotStatusCode",
    "evi2_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_MeasVDC",
    "evi2_target_current": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCCurrent",
    "evi2_target_voltage": "ns=1;s=R1:EVI_P2.OLI.EVSE_OutDCVoltage",
    "evi2_soc": "ns=1;s=R1:EVI_P2.OLI.SOC",
    "evi2_ack": "ns=1;s=R1:B_Ack2",
    "evi2_es": "ns=1;s=R1:B_ES2",
    "evi2_temp1": "ns=1;s=R1:EVI_P2.OLI.Temp1",
    "evi2_temp2": "ns=1;s=R1:EVI_P2.OLI.Temp2",
    "dcbm2_temp_h": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureH",
    "dcbm2_temp_l": "ns=1;s=R1:DCBM2.LiveMesure.TemperatureL",
    
    "seq23_ready": "ns=1;s=R1:seq23.b_ready",
    "seq23_fault": "ns=1;s=R1:SEQ23_OBI_ICPCFlt",
    "seq23_ic": "ns=1;s=R1:SEQ23.OLI.A.IC1",
    "seq23_pc": "ns=1;s=R1:SEQ23.OLI.A.PC1",
    "seq23_branch": "ns=1;s=R1:SEQ23.OLI.Branch_01",
    "seq23_ack": "ns=1;s=R1:seq23.ibi.ackcmd",
    "seq23_hmi": "ns=1;s=R1:SEQ23HMI.OLI.Branch_01",

    "hc2p4_current": "ns=1;s=R1:hc2.ori.hb2measi",
    "hc2p4_voltage": "ns=1;s=R1:hc2.ori.hb2measv",
    "pdc4_plim": "ns=1;s=R1:PDCx_R_PLim[4]",
    
    "evi4_cp_status": "ns=1;s=R1:EVI_P4.OLI.CP_StatusCode",
    "evi4_substatus": "ns=1;s=R1:EVI_P4.OLI.CP_SubStatusCode",
    "evi4_error": "ns=1;s=R1:EVI_P4.OLI.CP_ErrorCode",
    "evi4_pilot": "ns=1;s=R1:EVI_P4.OLI.PilotStatusCode",
    "evi4_voltage": "ns=1;s=R1:EVI_P4.OLI.EVSE_MeasVDC",
    "evi4_target_current": "ns=1;s=R1:EVI_P4.OLI.EVSE_OutDCCurrent",
    "evi4_target_voltage": "ns=1;s=R1:EVI_P4.OLI.EVSE_OutDCVoltage",
    "evi4_soc": "ns=1;s=R1:EVI_P4.OLI.SOC",
    "evi4_ack": "ns=1;s=R1:B_Ack4",
    "evi4_es": "ns=1;s=R1:B_ES4",
    "evi4_temp1": "ns=1;s=R1:EVI_P4.OLI.Temp1",
    "evi4_temp2": "ns=1;s=R1:EVI_P4.OLI.Temp2",
    "dcbm4_temp_h": "ns=1;s=R1:DCBM4.LiveMesure.TemperatureH",
    "dcbm4_temp_l": "ns=1;s=R1:DCBM4.LiveMesure.TemperatureL",
    
    "seq14_ready": "ns=1;s=R1:seq14.b_ready",
    "seq14_fault": "ns=1;s=R1:SEQ14_OBI_ICPCFlt",
    "seq14_ic": "ns=1;s=R1:SEQ14.OLI.A.IC1",
    "seq14_pc": "ns=1;s=R1:SEQ14.OLI.A.PC1",
    "seq14_branch": "ns=1;s=R1:SEQ14.OLI.Branch_01",
    "seq14_ack": "ns=1;s=R1:seq14.ibi.ackcmd",
    "seq14_hmi": "ns=1;s=R1:SEQ14HMI.OLI.Branch_01",

    "ntp_sync": "ns=1;s=R1:Gen_DiagAMS.OBI_IsNTPSync",
    "sys_version": "ns=1;s=R1:Gen_DiagAMS.OMI_SysVersion",
    "sys_name": "ns=1;s=R1:Gen_DiagAMS.OMI_Name",
    "sw_version": "ns=1;s=R1:Gen_DiagAMS.OMI_SW",

    "pdc1_status_text": "ns=1;s=R1:pdc1_cs_status.pdc_s_status",
    "pdc1_status_color": "ns=1;s=R1:PDC1_CS_Status.PDC_L_CoulourStatus",
    "pdc2_status_text": "ns=1;s=R1:pdc2_cs_status.pdc_s_status",
    "pdc2_status_color": "ns=1;s=R1:PDC2_CS_Status.PDC_L_CoulourStatus",
    "pdc1_manu_indispo": "ns=1;s=R1:PDC1_B_ManuIndispo",
    "pdc2_manu_indispo": "ns=1;s=R1:PDC2_B_ManuIndispo",
    "tilt_sensor_pdc12": "ns=1;s=R1:P1P2_OBI_TiltSensor_Flt",
    "pdc12_ack_tilt": "ns=1;s=R1:P1P2_B_AckTilt",
    "pdc12_restart": "ns=1;s=R1:PDC12_B_Restart",
    "endpoint12_ok": "ns=1;s=R1:OCPP201_B_EndPoint12_Connected",
    "evip1_remote_unavailable": "ns=1;s=R1:EVIP1_OCPP.OBI.RemoteSetUnvailable",
    "evip2_remote_unavailable": "ns=1;s=R1:EVIP2_OCPP.OBI.RemoteSetUnvailable",

    "pdc3_status_text": "ns=1;s=R1:pdc3_cs_status.pdc_s_status",
    "pdc3_status_color": "ns=1;s=R1:PDC3_CS_Status.PDC_L_CoulourStatus",
    "pdc4_status_text": "ns=1;s=R1:pdc4_cs_status.pdc_s_status",
    "pdc4_status_color": "ns=1;s=R1:PDC4_CS_Status.PDC_L_CoulourStatus",
    "pdc3_manu_indispo": "ns=1;s=R1:PDC3_B_ManuIndispo",
    "pdc4_manu_indispo": "ns=1;s=R1:PDC4_B_ManuIndispo",
    "tilt_sensor_pdc34": "ns=1;s=R1:P3P4_OBI_TiltSensor_Flt",
    "pdc34_ack_tilt": "ns=1;s=R1:P3P4_B_AckTilt",
    "pdc34_restart": "ns=1;s=R1:PDC34_B_Restart",
    "endpoint34_ok": "ns=1;s=R1:OCPP201_B_EndPoint34_Connected",
    "evip3_remote_unavailable": "ns=1;s=R1:EVIP3_OCPP.OBI.RemoteSetUnvailable",
    "evip4_remote_unavailable": "ns=1;s=R1:EVIP4_OCPP.OBI.RemoteSetUnvailable",

    "paiement_bypass_12": "ns=1;s=R1:B_SET_FreeMode_PDC12",
    "paiement_bypass_34": "ns=1;s=R1:B_SET_FreeMode_PDC34",

    "mxrx_1_com":"ns=1;s=R1:MXRx[1].OBI.ComOK",
    "mxrx_2_com":"ns=1;s=R1:MXRx[2].OBI.ComOK",
    "mxrx_3_com":"ns=1;s=R1:MXRx[3].OBI.ComOK",
    "mxrx_4_com":"ns=1;s=R1:MXRx[4].OBI.ComOK",
    "mxrx_5_com":"ns=1;s=R1:MXRx[5].OBI.ComOK",
    "mxrx_6_com":"ns=1;s=R1:MXRx[6].OBI.ComOK",
    "mxrx_7_com":"ns=1;s=R1:MXRx[7].OBI.ComOK",
    "mxrx_8_com":"ns=1;s=R1:MXRx[8].OBI.ComOK",
    "mxrx_9_com":"ns=1;s=R1:MXRx[9].OBI.ComOK",
    "mxrx_10_com":"ns=1;s=R1:MXRx[10].OBI.ComOK",
    "mxrx_11_com":"ns=1;s=R1:MXRx[11].OBI.ComOK",
    "mxrx_12_com":"ns=1;s=R1:MXRx[12].OBI.ComOK",
    "mxrx_13_com":"ns=1;s=R1:MXRx[13].OBI.ComOK",
    "mxrx_14_com":"ns=1;s=R1:MXRx[14].OBI.ComOK"

}

SYNOPTIQUE_VARIABLES = {
    "pg1_status": "ns=1;s=R1:pgx[1].oli.status",
    "pg2_status": "ns=1;s=R1:pgx[2].oli.status",
    "pg3_status": "ns=1;s=R1:pgx[3].oli.status",
    "pg4_status": "ns=1;s=R1:pgx[4].oli.status",
    "pg5_status": "ns=1;s=R1:pgx[5].oli.status",
    "pg6_status": "ns=1;s=R1:pgx[6].oli.status",
    "pg7_status": "ns=1;s=R1:pgx[7].oli.status",
    "pg8_status": "ns=1;s=R1:pgx[8].oli.status",
    "pg9_status": "ns=1;s=R1:pgx[9].oli.status",
    "pg10_status": "ns=1;s=R1:pgx[10].oli.status",

    "pg1_color_id": "ns=1;s=R1:pgx_l_colorid[1]",
    "pg2_color_id": "ns=1;s=R1:pgx_l_colorid[2]",
    "pg3_color_id": "ns=1;s=R1:pgx_l_colorid[3]",
    "pg4_color_id": "ns=1;s=R1:pgx_l_colorid[4]",
    "pg5_color_id": "ns=1;s=R1:pgx_l_colorid[5]",
    "pg6_color_id": "ns=1;s=R1:pgx_l_colorid[6]",
    "pg7_color_id": "ns=1;s=R1:pgx_l_colorid[7]",
    "pg8_color_id": "ns=1;s=R1:pgx_l_colorid[8]",
    "pg9_color_id": "ns=1;s=R1:pgx_l_colorid[9]",
    "pg10_color_id": "ns=1;s=R1:pgx_l_colorid[10]",

    "pg1_id_prise": "ns=1;s=R1:pgx[1].oli.idprise",
    "pg2_id_prise": "ns=1;s=R1:pgx[2].oli.idprise",
    "pg3_id_prise": "ns=1;s=R1:pgx[3].oli.idprise",
    "pg4_id_prise": "ns=1;s=R1:pgx[4].oli.idprise",
    "pg5_id_prise": "ns=1;s=R1:pgx[5].oli.idprise",
    "pg6_id_prise": "ns=1;s=R1:pgx[6].oli.idprise",
    "pg7_id_prise": "ns=1;s=R1:pgx[7].oli.idprise",
    "pg8_id_prise": "ns=1;s=R1:pgx[8].oli.idprise",
    "pg9_id_prise": "ns=1;s=R1:pgx[9].oli.idprise",
    "pg10_id_prise": "ns=1;s=R1:pgx[10].oli.idprise",

    "m1_status": "ns=1;s=R1:mxrx[1].oli.status",
    "m2_status": "ns=1;s=R1:mxrx[2].oli.status",
    "m3_status": "ns=1;s=R1:mxrx[3].oli.status",
    "m4_status": "ns=1;s=R1:mxrx[4].oli.status",
    "m5_status": "ns=1;s=R1:mxrx[5].oli.status",
    "m6_status": "ns=1;s=R1:mxrx[6].oli.status",
    "m7_status": "ns=1;s=R1:mxrx[7].oli.status",
    "m8_status": "ns=1;s=R1:mxrx[8].oli.status",
    "m9_status": "ns=1;s=R1:mxrx[9].oli.status",
    "m10_status": "ns=1;s=R1:mxrx[10].oli.status",
    "m11_status": "ns=1;s=R1:mxrx[11].oli.status",
    "m12_status": "ns=1;s=R1:mxrx[12].oli.status",
    "m13_status": "ns=1;s=R1:mxrx[13].oli.status",
    "m14_status": "ns=1;s=R1:mxrx[14].oli.status",

    "m1_vdc": "ns=1;s=R1:mxrx[1].ori.outmeasvdc",
    "m2_vdc": "ns=1;s=R1:mxrx[2].ori.outmeasvdc",
    "m3_vdc": "ns=1;s=R1:mxrx[3].ori.outmeasvdc",
    "m4_vdc": "ns=1;s=R1:mxrx[4].ori.outmeasvdc",
    "m5_vdc": "ns=1;s=R1:mxrx[5].ori.outmeasvdc",
    "m6_vdc": "ns=1;s=R1:mxrx[6].ori.outmeasvdc",
    "m7_vdc": "ns=1;s=R1:mxrx[7].ori.outmeasvdc",
    "m8_vdc": "ns=1;s=R1:mxrx[8].ori.outmeasvdc",
    "m9_vdc": "ns=1;s=R1:mxrx[9].ori.outmeasvdc",
    "m10_vdc": "ns=1;s=R1:mxrx[10].ori.outmeasvdc",
    "m11_vdc": "ns=1;s=R1:mxrx[11].ori.outmeasvdc",
    "m12_vdc": "ns=1;s=R1:mxrx[12].ori.outmeasvdc",
    "m13_vdc": "ns=1;s=R1:mxrx[13].ori.outmeasvdc",
    "m14_vdc": "ns=1;s=R1:mxrx[14].ori.outmeasvdc",

    "m1_idc": "ns=1;s=R1:mxrx[1].ori.outmeascurrent",
    "m2_idc": "ns=1;s=R1:mxrx[2].ori.outmeascurrent",
    "m3_idc": "ns=1;s=R1:mxrx[3].ori.outmeascurrent",
    "m4_idc": "ns=1;s=R1:mxrx[4].ori.outmeascurrent",
    "m5_idc": "ns=1;s=R1:mxrx[5].ori.outmeascurrent",
    "m6_idc": "ns=1;s=R1:mxrx[6].ori.outmeascurrent",
    "m7_idc": "ns=1;s=R1:mxrx[7].ori.outmeascurrent",
    "m8_idc": "ns=1;s=R1:mxrx[8].ori.outmeascurrent",
    "m9_idc": "ns=1;s=R1:mxrx[9].ori.outmeascurrent",
    "m10_idc": "ns=1;s=R1:mxrx[10].ori.outmeascurrent",
    "m11_idc": "ns=1;s=R1:mxrx[11].ori.outmeascurrent",
    "m12_idc": "ns=1;s=R1:mxrx[12].ori.outmeascurrent",
    "m13_idc": "ns=1;s=R1:mxrx[13].ori.outmeascurrent",
    "m14_idc": "ns=1;s=R1:mxrx[14].ori.outmeascurrent",

    "km1_status": "ns=1;s=R1:kmx_mvt[1].oli.status",
    "km2_status": "ns=1;s=R1:kmx_mvt[2].oli.status",
    "km3_status": "ns=1;s=R1:kmx_mvt[3].oli.status",
    "km4_status": "ns=1;s=R1:kmx_mvt[4].oli.status",
    "km5_status": "ns=1;s=R1:kmx_mvt[5].oli.status",
    "km6_status": "ns=1;s=R1:kmx_mvt[6].oli.status",
    "km7_status": "ns=1;s=R1:kmx_mvt[7].oli.status",
    "km8_status": "ns=1;s=R1:kmx_mvt[8].oli.status",
    "km9_status": "ns=1;s=R1:kmx_mvt[9].oli.status",
    "km10_status": "ns=1;s=R1:kmx_mvt[10].oli.status",
    "km11_status": "ns=1;s=R1:kmx_mvt[11].oli.status",
    "km12_status": "ns=1;s=R1:kmx_mvt[12].oli.status",

    "p1_status": "ns=1;s=R1:px_mvt[1].oli.status",
    "p2_status": "ns=1;s=R1:px_mvt[2].oli.status",
    "p3_status": "ns=1;s=R1:px_mvt[3].oli.status",
    "p4_status": "ns=1;s=R1:px_mvt[4].oli.status",

    "pdc1_color_status": "ns=1;s=R1:pdc1_cs_status.pdc_l_coulourstatus",
    "pdc2_color_status": "ns=1;s=R1:pdc2_cs_status.pdc_l_coulourstatus",
    "pdc3_color_status": "ns=1;s=R1:pdc3_cs_status.pdc_l_coulourstatus",
    "pdc4_color_status": "ns=1;s=R1:pdc4_cs_status.pdc_l_coulourstatus",

    "pdc1_text_status": "ns=1;s=R1:pdc1_cs_status.pdc_s_status",
    "pdc2_text_status": "ns=1;s=R1:pdc2_cs_status.pdc_s_status",
    "pdc3_text_status": "ns=1;s=R1:pdc3_cs_status.pdc_s_status",
    "pdc4_text_status": "ns=1;s=R1:pdc4_cs_status.pdc_s_status",
}

