import random

OFFLINE_DATA = {
    "rio_comflt": False,
    "evi_p1_comok": True,
    "evi_p2_comok": True,
    "evi_p3_comok": True,
    "evi_p4_comok": True,
    "bess_comflt": False,
    "jbox": True,
    "hmi_service_12": False,
    "cs_service_12": False,
    "hmi_service_34": False,
    "cs_service_34": False,
    "dcbm1_comflt": False,
    "dcbm2_comflt": False,
    "dcbm3_comflt": False,
    "dcbm4_comflt": False,

    "seq12_ready": True,
    "seq12_fault": False,
    "seq12_ic": 125.5,
    "seq12_pc": 180.3,
    "seq12_branch": 1,
    "seq12_ack": False,
    "seq12_hmi": 1,

    "hc1p1_current": 142.7,
    "hc1p1_voltage": 785.2,
    "pdc1_plim": 150.0,

    "evi1_cp_status": 3,
    "evi1_substatus": 0,
    "evi1_error": 0,
    "evi1_pilot": 2,
    "evi1_voltage": 780.5,
    "evi1_target_current": 150.0,
    "evi1_target_voltage": 800.0,
    "evi1_soc": 65.8,
    "evi1_ack": False,
    "evi1_es": False,
    "evi1_temp1": 32.5,
    "evi1_temp2": 34.1,
    "dcbm1_temp_h": 38.2,
    "dcbm1_temp_l": 35.7,

    "seq13_ready": True,
    "seq13_fault": False,
    "seq13_ic": 118.3,
    "seq13_pc": 175.8,
    "seq13_branch": 1,
    "seq13_ack": False,
    "seq13_hmi": 1,

    "hc2p3_current": 135.4,
    "hc2p3_voltage": 792.1,
    "pdc3_plim": 150.0,

    "evi3_cp_status": 3,
    "evi3_substatus": 0,
    "evi3_error": 0,
    "evi3_pilot": 2,
    "evi3_voltage": 788.3,
    "evi3_target_current": 150.0,
    "evi3_target_voltage": 800.0,
    "evi3_soc": 72.4,
    "evi3_ack": False,
    "evi3_es": False,
    "evi3_temp1": 33.7,
    "evi3_temp2": 35.2,
    "dcbm3_temp_h": 37.5,
    "dcbm3_temp_l": 36.1,

    "seq04_branch": 1,
    "seq04_start": False,
    "seq04_stop": False,
    "seq04_ack": False,
    "seq04_ic": 0.0,
    "seq04_pc": 0.0,
    "seq04_ready": True,
    "seq04_fault": False,

    "seq22_ready": True,
    "seq22_fault": False,
    "seq22_ic": 130.2,
    "seq22_pc": 182.6,
    "seq22_branch": 1,
    "seq22_ack": False,
    "seq22_hmi": 1,

    "hc1p2_current": 148.6,
    "hc1p2_voltage": 778.9,
    "pdc2_plim": 150.0,

    "evi2_cp_status": 3,
    "evi2_substatus": 0,
    "evi2_error": 0,
    "evi2_pilot": 2,
    "evi2_voltage": 775.2,
    "evi2_target_current": 150.0,
    "evi2_target_voltage": 800.0,
    "evi2_soc": 58.3,
    "evi2_ack": False,
    "evi2_es": False,
    "evi2_temp1": 31.8,
    "evi2_temp2": 33.5,
    "dcbm2_temp_h": 39.1,
    "dcbm2_temp_l": 36.8,

    "seq23_ready": True,
    "seq23_fault": False,
    "seq23_ic": 122.9,
    "seq23_pc": 178.4,
    "seq23_branch": 1,
    "seq23_ack": False,
    "seq23_hmi": 1,

    "hc2p4_current": 139.7,
    "hc2p4_voltage": 783.6,
    "pdc4_plim": 150.0,

    "evi4_cp_status": 3,
    "evi4_substatus": 0,
    "evi4_error": 0,
    "evi4_pilot": 2,
    "evi4_voltage": 781.7,
    "evi4_target_current": 150.0,
    "evi4_target_voltage": 800.0,
    "evi4_soc": 81.2,
    "evi4_ack": False,
    "evi4_es": False,
    "evi4_temp1": 34.3,
    "evi4_temp2": 35.9,
    "dcbm4_temp_h": 38.8,
    "dcbm4_temp_l": 37.2,

    "seq14_ready": True,
    "seq14_fault": False,
    "seq14_ic": 0.0,
    "seq14_pc": 0.0,
    "seq14_branch": 0,
    "seq14_ack": False,
    "seq14_hmi": 0,

    "ntp_sync": True,
    "sys_version": "v2.3.1",
    "sys_name": "IECV2-OFFLINE",
    "sw_version": "2.3.1-offline",

    "pdc1_status_text": "Disponible",
    "pdc1_status_color": 2,
    "pdc2_status_text": "Charge en cours",
    "pdc2_status_color": 3,
    "pdc3_status_text": "Disponible",
    "pdc3_status_color": 2,
    "pdc4_status_text": "Disponible",
    "pdc4_status_color": 2,
    "pdc1_manu_indispo": False,
    "pdc2_manu_indispo": False,
    "pdc3_manu_indispo": False,
    "pdc4_manu_indispo": False,
    "tilt_sensor_pdc12": False,
    "pdc12_ack_tilt": False,
    "pdc12_restart": False,
    "endpoint12_ok": True,
    "evip1_remote_unavailable": False,
    "evip2_remote_unavailable": False,
    "tilt_sensor_pdc34": False,
    "pdc34_ack_tilt": False,
    "pdc34_restart": False,
    "endpoint34_ok": True,
    "evip3_remote_unavailable": False,
    "evip4_remote_unavailable": False,

    "paiement_bypass_12": False,
    "paiement_bypass_34": False,

    "mxrx_1_com": True,
    "mxrx_2_com": True,
    "mxrx_3_com": True,
    "mxrx_4_com": True,
    "mxrx_5_com": True,
    "mxrx_6_com": True,
    "mxrx_7_com": True,
    "mxrx_8_com": True,
    "mxrx_9_com": True,
    "mxrx_10_com": True,
    "mxrx_11_com": True,
    "mxrx_12_com": True,
    "mxrx_13_com": True,
    "mxrx_14_com": True,
}

SYNOPTIQUE_OFFLINE_DATA = {
    "pg1_status": 2,
    "pg2_status": 3,
    "pg3_status": 2,
    "pg4_status": 2,
    "pg5_status": 1,
    "pg6_status": 1,
    "pg7_status": 1,
    "pg8_status": 1,
    "pg9_status": 1,
    "pg10_status": 1,

    "pg1_color_id": 2,
    "pg2_color_id": 3,
    "pg3_color_id": 2,
    "pg4_color_id": 2,
    "pg5_color_id": 1,
    "pg6_color_id": 1,
    "pg7_color_id": 1,
    "pg8_color_id": 1,
    "pg9_color_id": 1,
    "pg10_color_id": 1,

    "pg1_id_prise": 1,
    "pg2_id_prise": 2,
    "pg3_id_prise": 3,
    "pg4_id_prise": 4,
    "pg5_id_prise": 0,
    "pg6_id_prise": 0,
    "pg7_id_prise": 0,
    "pg8_id_prise": 0,
    "pg9_id_prise": 0,
    "pg10_id_prise": 0,

    "m1_status": 3,
    "m2_status": 3,
    "m3_status": 3,
    "m4_status": 3,
    "m5_status": 3,
    "m6_status": 3,
    "m7_status": 3,
    "m8_status": 3,
    "m9_status": 3,
    "m10_status": 3,
    "m11_status": 1,
    "m12_status": 1,
    "m13_status": 1,
    "m14_status": 1,

    "m1_vdc": 785.3,
    "m2_vdc": 782.1,
    "m3_vdc": 788.5,
    "m4_vdc": 790.2,
    "m5_vdc": 783.7,
    "m6_vdc": 787.9,
    "m7_vdc": 786.4,
    "m8_vdc": 789.1,
    "m9_vdc": 784.8,
    "m10_vdc": 791.3,
    "m11_vdc": 0.0,
    "m12_vdc": 0.0,
    "m13_vdc": 0.0,
    "m14_vdc": 0.0,

    "m1_idc": 142.5,
    "m2_idc": 138.7,
    "m3_idc": 145.2,
    "m4_idc": 140.8,
    "m5_idc": 143.6,
    "m6_idc": 141.9,
    "m7_idc": 139.4,
    "m8_idc": 144.1,
    "m9_idc": 142.3,
    "m10_idc": 146.7,
    "m11_idc": 0.0,
    "m12_idc": 0.0,
    "m13_idc": 0.0,
    "m14_idc": 0.0,

    "km1_status": 3,
    "km2_status": 3,
    "km3_status": 3,
    "km4_status": 3,
    "km5_status": 3,
    "km6_status": 3,
    "km7_status": 3,
    "km8_status": 3,
    "km9_status": 3,
    "km10_status": 3,
    "km11_status": 1,
    "km12_status": 1,

    "p1_status": 3,
    "p2_status": 3,
    "p3_status": 3,
    "p4_status": 3,

    "pdc1_color_status": 2,
    "pdc2_color_status": 3,
    "pdc3_color_status": 2,
    "pdc4_color_status": 2,

    "pdc1_text_status": "Disponible",
    "pdc2_text_status": "Charge en cours",
    "pdc3_text_status": "Disponible",
    "pdc4_text_status": "Disponible",
}

def get_offline_value(var_name):
    if var_name in OFFLINE_DATA:
        return OFFLINE_DATA[var_name]
    if var_name in SYNOPTIQUE_OFFLINE_DATA:
        return SYNOPTIQUE_OFFLINE_DATA[var_name]
    return None

def simulate_dynamic_value(var_name, current_value):
    if "current" in var_name or "_ic" in var_name or "_idc" in var_name:
        return current_value + random.uniform(-2.0, 2.0)
    elif "voltage" in var_name or "_pc" in var_name or "_vdc" in var_name:
        return current_value + random.uniform(-5.0, 5.0)
    elif "soc" in var_name:
        return min(100.0, current_value + random.uniform(0.0, 0.5))
    elif "temp" in var_name:
        return current_value + random.uniform(-0.5, 0.5)
    return current_value
